services:
  - type: web
    name: midquest-blog-api
    env: node
    plan: free
    rootDir: .
    buildCommand: yarn install --frozen-lockfile && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: DATABASE_URL
        fromDatabase:
          name: midquest-blog-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
